export const SERVICE_TYPES = [
  {
    id: "plumber",
    name: "Plumbing",
    icon: "🔧",
    color: "bg-blue-500",
    description: "Pipe repair, fixture installation, drain cleaning",
    image: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=400",
  },
  {
    id: "electrician",
    name: "Electrical",
    icon: "⚡",
    color: "bg-yellow-500",
    description: "Wiring, switch repair, appliance installation",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400",
  },
  {
    id: "painter",
    name: "Painting",
    icon: "🎨",
    color: "bg-purple-500",
    description: "Interior & exterior painting, wall textures",
    image: "https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=400",
  },
  {
    id: "mason",
    name: "Masonry",
    icon: "🧱",
    color: "bg-orange-500",
    description: "Brick work, plastering, tile setting",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400",
  },
  {
    id: "cleaner",
    name: "Cleaning",
    icon: "🧹",
    color: "bg-green-500",
    description: "Deep cleaning, pest control, sanitization",
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400",
  },
  {
    id: "carpenter",
    name: "Carpentry",
    icon: "🪚",
    color: "bg-amber-700",
    description: "Furniture repair, woodwork, cabinet installation",
    image: "https://images.unsplash.com/photo-1588854337115-1c67d9247e4d?w=400",
  },
];

export const BOOKING_STATUS = {
  pending: {
    label: "Pending",
    color: "bg-yellow-100 text-yellow-800",
    dot: "bg-yellow-500",
  },
  accepted: {
    label: "Accepted",
    color: "bg-blue-100 text-blue-800",
    dot: "bg-blue-500",
  },
  rejected: {
    label: "Rejected",
    color: "bg-red-100 text-red-800",
    dot: "bg-red-500",
  },
  completed: {
    label: "Completed",
    color: "bg-green-100 text-green-800",
    dot: "bg-green-500",
  },
  cancelled: {
    label: "Cancelled",
    color: "bg-gray-100 text-gray-800",
    dot: "bg-gray-500",
  },
};

export const PAYMENT_STATUS = {
  pending: { label: "Pending", color: "text-yellow-600" },
  paid: { label: "Paid", color: "text-green-600" },
  refunded: { label: "Refunded", color: "text-red-600" },
};

export const TESTIMONIALS = [
  {
    name: "Anita Sharma",
    role: "Homeowner",
    rating: 5,
    text: "Excellent plumbing service! Rajesh fixed our kitchen sink in under an hour. Very professional and clean work.",
    avatar: "👩",
  },
  {
    name: "Vikram Patel",
    role: "Apartment Owner",
    rating: 5,
    text: "The electrician was incredibly skilled. Fixed all the wiring issues and even suggested energy-saving solutions.",
    avatar: "👨",
  },
  {
    name: "Meera Krishnan",
    role: "Villa Owner",
    rating: 4,
    text: "Great painting work for our entire house. The team was punctual and the finish quality is outstanding.",
    avatar: "👩",
  },
  {
    name: "Arjun Reddy",
    role: "Homeowner",
    rating: 5,
    text: "Best cleaning service in Bangalore! They transformed our home. Will definitely book again.",
    avatar: "👨",
  },
];

// Demo providers for offline/frontend-only mode
export const DEMO_PROVIDERS = [
  {
    _id: "prv001",
    userId: {
      name: "Rajesh Kumar",
      phone: "9876543201",
      profileImage: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    serviceType: "plumber",
    experience: 8,
    rating: 4.8,
    totalBookings: 156,
    totalReviews: 94,
    pricePerHour: 500,
    availability: true,
    description:
      "Expert plumber with 8+ years experience. Specializing in pipe repair, leak fixing, and bathroom fitting installations.",
    skills: [
      "Pipe Repair",
      "Leak Fixing",
      "Bathroom Fitting",
      "Water Heater Installation",
    ],
    location: { area: "Koramangala", city: "Bangalore", pincode: "560034" },
  },
  {
    _id: "prv002",
    userId: {
      name: "Suresh Babu",
      phone: "9876543202",
      profileImage: "https://randomuser.me/api/portraits/men/45.jpg",
    },
    serviceType: "plumber",
    experience: 12,
    rating: 4.9,
    totalBookings: 210,
    totalReviews: 126,
    pricePerHour: 600,
    availability: true,
    description:
      "Master plumber specializing in complete bathroom renovations and complex pipeline systems.",
    skills: [
      "Pipeline Systems",
      "Bathroom Renovation",
      "Drain Cleaning",
      "Fixture Installation",
    ],
    location: { area: "Indiranagar", city: "Bangalore", pincode: "560038" },
  },
  {
    _id: "prv003",
    userId: {
      name: "Manjunath R",
      phone: "9876543203",
      profileImage: "https://randomuser.me/api/portraits/men/22.jpg",
    },
    serviceType: "plumber",
    experience: 5,
    rating: 4.5,
    totalBookings: 89,
    totalReviews: 53,
    pricePerHour: 400,
    availability: true,
    description:
      "Reliable plumber for all types of plumbing needs. Quick response and quality work.",
    skills: [
      "General Plumbing",
      "Tap Repair",
      "Toilet Repair",
      "Kitchen Plumbing",
    ],
    location: { area: "HSR Layout", city: "Bangalore", pincode: "560102" },
  },
  {
    _id: "prv004",
    userId: {
      name: "Ravi Shankar",
      phone: "9876543204",
      profileImage: "https://randomuser.me/api/portraits/men/67.jpg",
    },
    serviceType: "plumber",
    experience: 6,
    rating: 4.6,
    totalBookings: 102,
    totalReviews: 61,
    pricePerHour: 450,
    availability: true,
    description:
      "Professional plumber offering affordable and timely services.",
    skills: [
      "Water Tank Repair",
      "Pipe Fitting",
      "Drainage",
      "Motor Pump Service",
    ],
    location: { area: "Whitefield", city: "Bangalore", pincode: "560066" },
  },
  {
    _id: "prv005",
    userId: {
      name: "Venkatesh Iyer",
      phone: "9876543205",
      profileImage: "https://randomuser.me/api/portraits/men/11.jpg",
    },
    serviceType: "electrician",
    experience: 10,
    rating: 4.7,
    totalBookings: 180,
    totalReviews: 108,
    pricePerHour: 550,
    availability: true,
    description:
      "Certified electrician with expertise in residential and commercial electrical work.",
    skills: [
      "Wiring",
      "Switch Board Repair",
      "MCB Installation",
      "Fan Installation",
    ],
    location: { area: "Jayanagar", city: "Bangalore", pincode: "560041" },
  },
  {
    _id: "prv006",
    userId: {
      name: "Kiran Reddy",
      phone: "9876543206",
      profileImage: "https://randomuser.me/api/portraits/men/54.jpg",
    },
    serviceType: "electrician",
    experience: 7,
    rating: 4.8,
    totalBookings: 145,
    totalReviews: 87,
    pricePerHour: 500,
    availability: true,
    description:
      "Expert in smart home electrical setups and modern wiring solutions.",
    skills: [
      "Smart Home Wiring",
      "LED Installation",
      "Inverter Setup",
      "Earthing",
    ],
    location: { area: "BTM Layout", city: "Bangalore", pincode: "560076" },
  },
  {
    _id: "prv007",
    userId: {
      name: "Prakash Rao",
      phone: "9876543207",
      profileImage: "https://randomuser.me/api/portraits/men/76.jpg",
    },
    serviceType: "electrician",
    experience: 15,
    rating: 4.9,
    totalBookings: 320,
    totalReviews: 192,
    pricePerHour: 700,
    availability: true,
    description:
      "Master electrician with 15+ years. Specialist in commercial electrical solutions.",
    skills: [
      "Industrial Wiring",
      "Generator Setup",
      "UPS Installation",
      "Electrical Panel",
    ],
    location: { area: "MG Road", city: "Bangalore", pincode: "560001" },
  },
  {
    _id: "prv008",
    userId: {
      name: "Anand Kumar",
      phone: "9876543208",
      profileImage: "https://randomuser.me/api/portraits/men/88.jpg",
    },
    serviceType: "electrician",
    experience: 4,
    rating: 4.4,
    totalBookings: 67,
    totalReviews: 40,
    pricePerHour: 400,
    availability: true,
    description:
      "Young electrician with strong technical knowledge. Affordable rates.",
    skills: [
      "Appliance Repair",
      "Socket Installation",
      "Light Fixture",
      "CCTV Installation",
    ],
    location: { area: "Electronic City", city: "Bangalore", pincode: "560100" },
  },
  {
    _id: "prv009",
    userId: {
      name: "Arjun Das",
      phone: "9876543209",
      profileImage: "https://randomuser.me/api/portraits/men/33.jpg",
    },
    serviceType: "painter",
    experience: 9,
    rating: 4.6,
    totalBookings: 120,
    totalReviews: 72,
    pricePerHour: 450,
    availability: true,
    description:
      "Professional painter specializing in interior and exterior painting with premium finish.",
    skills: [
      "Interior Painting",
      "Exterior Painting",
      "Texture Painting",
      "Wood Polish",
    ],
    location: { area: "Marathahalli", city: "Bangalore", pincode: "560037" },
  },
  {
    _id: "prv010",
    userId: {
      name: "Deepak Singh",
      phone: "9876543210",
      profileImage: "https://randomuser.me/api/portraits/men/44.jpg",
    },
    serviceType: "painter",
    experience: 11,
    rating: 4.7,
    totalBookings: 175,
    totalReviews: 105,
    pricePerHour: 550,
    availability: true,
    description:
      "Creative painter specializing in artistic walls, stencil work, and designer finishes.",
    skills: [
      "Artistic Walls",
      "Stencil Work",
      "PU Finish",
      "Wallpaper Installation",
    ],
    location: { area: "Sarjapur Road", city: "Bangalore", pincode: "560035" },
  },
  {
    _id: "prv011",
    userId: {
      name: "Mohammed Ismail",
      phone: "9876543211",
      profileImage: "https://randomuser.me/api/portraits/men/29.jpg",
    },
    serviceType: "painter",
    experience: 6,
    rating: 4.5,
    totalBookings: 95,
    totalReviews: 57,
    pricePerHour: 400,
    availability: true,
    description:
      "Reliable painter offering quality painting services at competitive prices.",
    skills: ["Emulsion Paint", "Distemper", "Primer Coating", "Wall Putty"],
    location: { area: "JP Nagar", city: "Bangalore", pincode: "560078" },
  },
  {
    _id: "prv012",
    userId: {
      name: "Srinivas Murthy",
      phone: "9876543212",
      profileImage: "https://randomuser.me/api/portraits/men/61.jpg",
    },
    serviceType: "painter",
    experience: 14,
    rating: 4.8,
    totalBookings: 250,
    totalReviews: 150,
    pricePerHour: 650,
    availability: true,
    description:
      "Expert painter with mastery over decorative finishes and luxury painting.",
    skills: [
      "Epoxy Coating",
      "Decorative Finish",
      "Water Proofing",
      "Spray Painting",
    ],
    location: { area: "Hebbal", city: "Bangalore", pincode: "560024" },
  },
  {
    _id: "prv013",
    userId: {
      name: "Gopal Krishna",
      phone: "9876543213",
      profileImage: "https://randomuser.me/api/portraits/men/90.jpg",
    },
    serviceType: "mason",
    experience: 20,
    rating: 4.9,
    totalBookings: 340,
    totalReviews: 204,
    pricePerHour: 700,
    availability: true,
    description:
      "Master mason with 20 years of experience in residential construction and renovation.",
    skills: ["Brick Work", "Plastering", "Tile Setting", "Concrete Work"],
    location: { area: "Basavanagudi", city: "Bangalore", pincode: "560004" },
  },
  {
    _id: "prv014",
    userId: {
      name: "Nagaraj M",
      phone: "9876543214",
      profileImage: "https://randomuser.me/api/portraits/men/51.jpg",
    },
    serviceType: "mason",
    experience: 10,
    rating: 4.6,
    totalBookings: 130,
    totalReviews: 78,
    pricePerHour: 550,
    availability: true,
    description:
      "Experienced mason specializing in kitchen and bathroom renovations.",
    skills: [
      "Kitchen Renovation",
      "Bathroom Renovation",
      "Waterproofing",
      "Foundation Work",
    ],
    location: { area: "Rajajinagar", city: "Bangalore", pincode: "560010" },
  },
  {
    _id: "prv015",
    userId: {
      name: "Basavaraj T",
      phone: "9876543215",
      profileImage: "https://randomuser.me/api/portraits/men/41.jpg",
    },
    serviceType: "mason",
    experience: 7,
    rating: 4.5,
    totalBookings: 88,
    totalReviews: 53,
    pricePerHour: 450,
    availability: true,
    description: "Skilled mason for all types of construction and repair work.",
    skills: ["Wall Construction", "Tiling", "Stone Work", "Renovation"],
    location: { area: "Yelahanka", city: "Bangalore", pincode: "560064" },
  },
  {
    _id: "prv016",
    userId: {
      name: "Ramesh Naidu",
      phone: "9876543216",
      profileImage: "https://randomuser.me/api/portraits/men/63.jpg",
    },
    serviceType: "mason",
    experience: 13,
    rating: 4.7,
    totalBookings: 195,
    totalReviews: 117,
    pricePerHour: 600,
    availability: true,
    description:
      "Expert in modern construction techniques and luxury interiors.",
    skills: [
      "Modern Construction",
      "Marble Work",
      "Granite Setting",
      "Interior Design",
    ],
    location: {
      area: "Bannerghatta Road",
      city: "Bangalore",
      pincode: "560076",
    },
  },
  {
    _id: "prv017",
    userId: {
      name: "Priya Sharma",
      phone: "9876543217",
      profileImage: "https://randomuser.me/api/portraits/women/45.jpg",
    },
    serviceType: "cleaner",
    experience: 5,
    rating: 4.7,
    totalBookings: 200,
    totalReviews: 120,
    pricePerHour: 350,
    availability: true,
    description:
      "Professional cleaner specializing in deep cleaning and move-in/move-out cleaning.",
    skills: [
      "Deep Cleaning",
      "Kitchen Cleaning",
      "Bathroom Sanitization",
      "Move-in Cleaning",
    ],
    location: { area: "Koramangala", city: "Bangalore", pincode: "560034" },
  },
  {
    _id: "prv018",
    userId: {
      name: "Lakshmi Devi",
      phone: "9876543218",
      profileImage: "https://randomuser.me/api/portraits/women/62.jpg",
    },
    serviceType: "cleaner",
    experience: 8,
    rating: 4.8,
    totalBookings: 280,
    totalReviews: 168,
    pricePerHour: 400,
    availability: true,
    description:
      "Expert in eco-friendly cleaning methods. Uses organic and safe products.",
    skills: [
      "Eco Cleaning",
      "Sofa Cleaning",
      "Carpet Cleaning",
      "Window Cleaning",
    ],
    location: { area: "Indiranagar", city: "Bangalore", pincode: "560038" },
  },
  {
    _id: "prv019",
    userId: {
      name: "Kavitha R",
      phone: "9876543219",
      profileImage: "https://randomuser.me/api/portraits/women/24.jpg",
    },
    serviceType: "cleaner",
    experience: 3,
    rating: 4.4,
    totalBookings: 60,
    totalReviews: 36,
    pricePerHour: 300,
    availability: true,
    description: "Reliable and thorough cleaning services at affordable rates.",
    skills: ["Regular Cleaning", "Dusting", "Mopping", "Pest Control"],
    location: { area: "Whitefield", city: "Bangalore", pincode: "560066" },
  },
  {
    _id: "prv020",
    userId: {
      name: "Sunita M",
      phone: "9876543220",
      profileImage: "https://randomuser.me/api/portraits/women/33.jpg",
    },
    serviceType: "cleaner",
    experience: 6,
    rating: 4.6,
    totalBookings: 150,
    totalReviews: 90,
    pricePerHour: 350,
    availability: true,
    description: "Thorough cleaning professional with attention to detail.",
    skills: [
      "Office Cleaning",
      "Post-Construction",
      "Mattress Cleaning",
      "Sanitization",
    ],
    location: { area: "HSR Layout", city: "Bangalore", pincode: "560102" },
  },
  {
    _id: "prv021",
    userId: {
      name: "Mahesh Kumar",
      phone: "9876543221",
      profileImage: "https://randomuser.me/api/portraits/men/68.jpg",
    },
    serviceType: "carpenter",
    experience: 12,
    rating: 4.8,
    totalBookings: 220,
    totalReviews: 132,
    pricePerHour: 550,
    availability: true,
    description:
      "Master carpenter specializing in custom furniture and modular kitchen installations.",
    skills: [
      "Custom Furniture",
      "Modular Kitchen",
      "Wardrobe Design",
      "Door Installation",
    ],
    location: { area: "Jayanagar", city: "Bangalore", pincode: "560041" },
  },
  {
    _id: "prv022",
    userId: {
      name: "Raju Shetty",
      phone: "9876543222",
      profileImage: "https://randomuser.me/api/portraits/men/72.jpg",
    },
    serviceType: "carpenter",
    experience: 8,
    rating: 4.6,
    totalBookings: 140,
    totalReviews: 84,
    pricePerHour: 500,
    availability: true,
    description:
      "Skilled carpenter for furniture repair, assembly, and wood polishing.",
    skills: [
      "Furniture Repair",
      "Wood Polish",
      "Cabinet Making",
      "Bed Assembly",
    ],
    location: { area: "BTM Layout", city: "Bangalore", pincode: "560076" },
  },
  {
    _id: "prv023",
    userId: {
      name: "Vishnu Prasad",
      phone: "9876543223",
      profileImage: "https://randomuser.me/api/portraits/men/55.jpg",
    },
    serviceType: "carpenter",
    experience: 15,
    rating: 4.9,
    totalBookings: 300,
    totalReviews: 180,
    pricePerHour: 700,
    availability: true,
    description: "Premium carpenter specializing in luxury wood interiors.",
    skills: [
      "Luxury Interiors",
      "Teak Furniture",
      "Wood Carving",
      "Partition Work",
    ],
    location: { area: "MG Road", city: "Bangalore", pincode: "560001" },
  },
  {
    _id: "prv024",
    userId: {
      name: "Santosh V",
      phone: "9876543224",
      profileImage: "https://randomuser.me/api/portraits/men/19.jpg",
    },
    serviceType: "carpenter",
    experience: 5,
    rating: 4.5,
    totalBookings: 75,
    totalReviews: 45,
    pricePerHour: 400,
    availability: true,
    description:
      "Affordable carpenter for everyday furniture needs and quick repairs.",
    skills: [
      "Quick Repairs",
      "Shelf Installation",
      "Lock Fitting",
      "Handle Replacement",
    ],
    location: { area: "Electronic City", city: "Bangalore", pincode: "560100" },
  },
];
